"""
Compact tool definitions. Each service's actions are listed as short suffixes;
the full tool name is reconstructed as {service}_{action} by generate().
"""

# Tool catalogue: {attribute: {service: [action_suffixes]}}
TOOLS_BY_SERVICE = {
    "payments": {
        "stripe": [
            "create_payment_intent", "get_payment_intent", "confirm_payment_intent",
            "cancel_payment_intent", "capture_payment_intent", "list_payment_intents", "update_payment_intent",
            "create_customer", "get_customer", "update_customer", "delete_customer", "list_customers", "search_customers",
            "create_subscription", "get_subscription", "update_subscription", "cancel_subscription",
            "pause_subscription", "resume_subscription", "list_subscriptions",
            "create_invoice", "get_invoice", "finalize_invoice", "pay_invoice",
            "void_invoice", "delete_invoice", "list_invoices", "send_invoice",
            "create_refund", "get_refund", "list_refunds",
            "get_charge", "capture_charge", "list_charges",
            "create_product", "update_product", "archive_product", "list_products",
            "create_price", "list_prices",
            "create_coupon", "delete_coupon", "list_coupons",
            "create_checkout_session", "expire_checkout_session",
            "get_balance", "list_balance_transactions",
            "create_payout", "list_payouts",
            "create_webhook", "delete_webhook", "list_webhooks",
        ],
        "paypal": [
            "create_order", "get_order", "capture_order", "authorize_order", "confirm_order",
            "refund_capture", "show_refund",
            "create_invoice", "send_invoice", "cancel_invoice", "get_invoice", "list_invoices", "pay_invoice",
            "create_billing_plan", "activate_plan", "deactivate_plan", "get_plan", "list_plans",
            "create_subscription", "get_subscription", "cancel_subscription",
            "suspend_subscription", "activate_subscription",
            "create_webhook", "delete_webhook", "list_webhooks",
            "get_account_info", "list_transactions", "get_payment", "list_payments",
        ],
    },
    "developer": {
        "github": [
            "list_repos", "get_repo", "create_repo", "delete_repo", "fork_repo", "transfer_repo",
            "list_branches", "get_branch", "create_branch", "delete_branch", "protect_branch", "merge_branches",
            "list_commits", "get_commit", "compare_commits",
            "list_pull_requests", "get_pull_request", "create_pull_request", "merge_pull_request",
            "close_pull_request", "create_review", "submit_review", "list_reviews",
            "list_issues", "get_issue", "create_issue", "update_issue", "close_issue",
            "add_label", "assign_issue",
            "list_workflows", "trigger_workflow", "get_workflow_run",
            "cancel_workflow_run", "list_workflow_runs",
            "list_releases", "create_release", "get_release", "delete_release",
            "get_file_content", "create_file", "update_file", "delete_file",
            "list_collaborators", "add_collaborator", "remove_collaborator",
            "list_webhooks", "create_webhook", "delete_webhook",
            "list_teams", "create_team", "delete_team", "add_team_member", "remove_team_member",
            "search_code", "search_issues", "search_repos",
            "get_user", "star_repo", "list_starred",
        ],
        "jira": [
            "create_issue", "get_issue", "update_issue", "delete_issue", "list_issues",
            "search_issues", "assign_issue", "transition_issue",
            "add_comment", "get_comment", "update_comment", "delete_comment", "list_comments",
            "create_project", "get_project", "update_project", "delete_project", "list_projects",
            "create_sprint", "start_sprint", "complete_sprint", "list_sprints", "get_sprint",
            "create_board", "get_board", "list_boards",
            "add_attachment", "list_attachments", "delete_attachment",
            "create_worklog", "update_worklog", "delete_worklog", "list_worklogs",
            "get_user", "list_users", "search_users",
            "create_version", "update_version", "release_version", "archive_version",
        ],
    },
    "messaging": {
        "slack": [
            "post_message", "update_message", "delete_message", "get_permalink",
            "schedule_message", "delete_scheduled_message",
            "list_channels", "create_channel", "archive_channel", "invite_to_channel", "rename_channel",
            "list_users", "get_user", "set_user_status", "get_user_profile",
            "upload_file", "list_files", "delete_file", "share_file",
            "add_reaction", "remove_reaction", "list_reactions",
            "pin_message", "unpin_message", "list_pins",
            "create_reminder", "list_reminders", "delete_reminder",
            "open_direct_message", "list_direct_messages",
        ],
        "sendgrid": [
            "send_email", "send_bulk_email",
            "create_template", "get_template", "update_template", "delete_template", "list_templates",
            "create_contact", "update_contact", "delete_contact", "list_contacts", "search_contacts",
            "create_list", "delete_list", "add_contacts_to_list",
            "get_stats", "get_click_stats", "get_open_stats",
            "create_api_key", "delete_api_key", "list_api_keys",
        ],
        "twilio": [
            "send_sms", "list_messages", "get_message", "delete_message",
            "make_call", "list_calls", "get_call", "cancel_call", "modify_call",
            "list_phone_numbers", "buy_phone_number", "release_phone_number",
            "create_conversation", "get_conversation", "list_conversations", "delete_conversation",
            "add_conversation_participant", "list_conversation_participants",
            "send_whatsapp", "list_whatsapp_messages",
            "create_flow", "delete_flow", "list_flows", "get_flow",
            "get_account", "list_subaccounts", "create_subaccount",
            "list_recordings", "delete_recording",
        ],
    },
    "crm": {
        "zendesk": [
            "create_ticket", "get_ticket", "update_ticket", "delete_ticket", "list_tickets",
            "search_tickets", "assign_ticket", "add_comment", "solve_ticket", "close_ticket", "merge_tickets",
            "create_user", "get_user", "update_user", "delete_user", "list_users",
            "search_users", "suspend_user",
            "create_organization", "get_organization", "update_organization",
            "delete_organization", "list_organizations",
            "list_macros", "create_macro", "apply_macro", "update_macro", "delete_macro",
            "list_views", "create_view", "get_view",
            "create_group", "list_groups", "add_user_to_group", "remove_user_from_group",
            "create_webhook", "delete_webhook", "list_webhooks",
            "get_satisfaction_rating", "list_satisfaction_ratings",
            "create_trigger", "update_trigger", "delete_trigger", "list_triggers",
        ],
        "hubspot": [
            "create_contact", "get_contact", "update_contact", "delete_contact",
            "list_contacts", "search_contacts", "merge_contacts",
            "create_company", "get_company", "update_company", "delete_company",
            "list_companies", "search_companies",
            "create_deal", "get_deal", "update_deal", "delete_deal", "list_deals", "close_deal",
            "create_task", "complete_task", "list_tasks", "update_task",
            "log_email", "log_call", "log_meeting", "list_activities",
            "create_pipeline", "list_pipelines", "get_pipeline", "update_pipeline",
        ],
    },
    "identity": {
        "auth0": [
            "create_user", "get_user", "update_user", "delete_user", "list_users",
            "search_users", "block_user", "unblock_user",
            "get_user_roles", "assign_role", "remove_role",
            "create_role", "delete_role", "get_role", "list_roles",
            "get_client", "create_client", "update_client", "delete_client", "list_clients",
            "get_connection", "list_connections", "create_connection",
            "update_connection", "delete_connection",
            "send_verification_email", "send_password_reset",
            "get_stats", "get_logs",
            "create_organization", "get_organization", "list_organizations", "delete_organization",
        ],
    },
    "analytics": {
        "mixpanel": [
            "track_event", "import_events", "list_events", "get_event_stats",
            "get_funnel", "list_funnels", "create_funnel",
            "get_retention", "get_segmentation",
            "create_user_profile", "update_user_profile", "delete_user_profile",
            "get_cohort", "list_cohorts", "create_cohort",
            "export_data", "get_project_info",
            "create_dashboard", "get_dashboard", "list_dashboards",
            "query_insights", "create_annotation", "list_annotations",
        ],
        "amplitude": [
            "track_event", "identify_user", "group_identify",
            "get_chart", "list_charts",
            "get_cohort", "list_cohorts",
            "export_events", "list_exports",
            "get_project_info",
            "create_annotation", "list_annotations",
            "query_api", "get_funnel_analysis", "get_retention_analysis",
        ],
    },
    "storage": {
        "gdrive": [
            "list_files", "get_file", "create_file", "update_file", "delete_file",
            "copy_file", "move_file", "rename_file",
            "upload_file", "download_file", "export_file",
            "list_folders", "create_folder", "delete_folder",
            "share_file", "list_permissions", "remove_permission", "update_permission",
            "list_comments", "create_comment", "delete_comment", "reply_to_comment",
            "list_revisions", "get_revision", "delete_revision",
            "add_to_starred", "remove_from_starred",
            "empty_trash", "list_trash",
        ],
        "notion": [
            "list_databases", "create_database", "query_database", "update_database",
            "list_pages", "create_page", "get_page", "update_page", "archive_page",
            "list_blocks", "get_block", "append_blocks", "delete_block", "update_block",
            "list_users", "get_user",
            "list_comments", "create_comment",
            "search",
        ],
        "airtable": [
            "list_bases", "get_base",
            "list_tables", "create_table", "update_table",
            "list_records", "get_record", "create_record", "update_record", "delete_record",
            "bulk_create_records", "bulk_update_records",
            "create_field", "update_field",
            "list_views", "get_view",
        ],
        "s3": [
            "list_buckets", "create_bucket", "delete_bucket", "get_bucket_policy", "put_bucket_policy",
            "list_objects", "get_object", "put_object", "delete_object", "copy_object",
            "create_presigned_url", "get_object_metadata",
            "set_versioning", "list_object_versions",
            "put_lifecycle_policy", "delete_lifecycle_policy",
            "enable_encryption", "set_cors_policy", "get_public_access_block",
        ],
        "docusign": [
            "create_envelope", "send_envelope", "get_envelope", "void_envelope", "list_envelopes",
            "list_recipients", "add_recipient", "delete_recipient",
            "get_document", "list_documents", "add_document",
            "create_template", "list_templates", "send_from_template",
            "get_status", "download_completed",
        ],
    },
}

# Non-standard params for specific tools. All others use verb-derived defaults.
# Format: [(param_name, json_type, required)]
PARAMS_OVERRIDE: dict = {
    "stripe_create_payment_intent": [("amount","integer",True),("currency","string",True),("customer","string",False),("description","string",False),("capture_method","string",False)],
    "stripe_create_refund": [("charge","string",False),("payment_intent","string",False),("amount","integer",False),("reason","string",False)],
    "stripe_create_subscription": [("customer","string",True),("price_id","string",True),("trial_period_days","integer",False)],
    "stripe_create_invoice": [("customer","string",True),("description","string",False),("due_date","integer",False)],
    "stripe_create_payout": [("amount","integer",True),("currency","string",True)],
    "stripe_create_checkout_session": [("success_url","string",True),("cancel_url","string",True),("line_items","array",True)],
    "paypal_create_order": [("intent","string",True),("currency_code","string",True),("value","string",True),("description","string",False)],
    "paypal_refund_capture": [("capture_id","string",True),("amount","object",False),("note_to_payer","string",False)],
    "github_create_pull_request": [("owner","string",True),("repo","string",True),("title","string",True),("head","string",True),("base","string",True),("body","string",False),("draft","boolean",False)],
    "github_trigger_workflow": [("owner","string",True),("repo","string",True),("workflow_id","string",True),("ref","string",True),("inputs","object",False)],
    "github_create_issue": [("owner","string",True),("repo","string",True),("title","string",True),("body","string",False),("labels","array",False),("assignees","array",False)],
    "github_merge_pull_request": [("owner","string",True),("repo","string",True),("pull_number","integer",True),("commit_title","string",False),("merge_method","string",False)],
    "jira_create_issue": [("project_key","string",True),("summary","string",True),("issue_type","string",True),("description","string",False),("assignee","string",False),("priority","string",False)],
    "jira_transition_issue": [("issue_key","string",True),("transition_name","string",True),("comment","string",False)],
    "jira_search_issues": [("jql","string",True),("max_results","integer",False),("fields","array",False)],
    "slack_post_message": [("channel","string",True),("text","string",True),("thread_ts","string",False),("blocks","array",False)],
    "slack_upload_file": [("channels","array",True),("filename","string",True),("content","string",False),("filetype","string",False),("title","string",False)],
    "slack_schedule_message": [("channel","string",True),("text","string",True),("post_at","integer",True)],
    "sendgrid_send_email": [("to","string",True),("from_email","string",True),("subject","string",True),("content","string",True),("template_id","string",False)],
    "sendgrid_send_bulk_email": [("to_list","array",True),("subject","string",True),("content","string",True),("from_email","string",True)],
    "twilio_send_sms": [("to","string",True),("from_","string",True),("body","string",True)],
    "twilio_make_call": [("to","string",True),("from_","string",True),("url","string",True)],
    "twilio_send_whatsapp": [("to","string",True),("from_","string",True),("body","string",True)],
    "twilio_buy_phone_number": [("phone_number","string",True),("area_code","string",False)],
    "zendesk_create_ticket": [("subject","string",True),("description","string",True),("priority","string",False),("assignee_id","integer",False),("tags","array",False)],
    "zendesk_add_comment": [("ticket_id","integer",True),("body","string",True),("public","boolean",False)],
    "zendesk_merge_tickets": [("target_id","integer",True),("source_ids","array",True),("reason","string",False)],
    "hubspot_create_contact": [("email","string",True),("firstname","string",False),("lastname","string",False),("company","string",False),("phone","string",False)],
    "hubspot_create_deal": [("dealname","string",True),("amount","string",False),("pipeline","string",False),("dealstage","string",False),("owner_id","string",False)],
    "hubspot_log_email": [("contact_id","string",True),("subject","string",True),("body","string",True),("timestamp","integer",False)],
    "auth0_create_user": [("email","string",True),("password","string",True),("connection","string",True),("name","string",False),("given_name","string",False)],
    "auth0_send_password_reset": [("email","string",True),("connection","string",True)],
    "mixpanel_track_event": [("event","string",True),("distinct_id","string",True),("properties","object",False)],
    "mixpanel_create_user_profile": [("distinct_id","string",True),("properties","object",True)],
    "mixpanel_get_funnel": [("funnel_id","integer",True),("from_date","string",True),("to_date","string",True)],
    "amplitude_track_event": [("event_type","string",True),("user_id","string",True),("event_properties","object",False)],
    "amplitude_identify_user": [("user_id","string",True),("user_properties","object",True)],
    "amplitude_get_funnel_analysis": [("funnel_id","string",True),("start_date","string",True),("end_date","string",True)],
    "gdrive_share_file": [("file_id","string",True),("email","string",True),("role","string",True),("type","string",False)],
    "gdrive_upload_file": [("name","string",True),("content","string",True),("parent_folder_id","string",False),("mime_type","string",False)],
    "s3_put_object": [("bucket","string",True),("key","string",True),("body","string",True),("content_type","string",False)],
    "s3_get_object": [("bucket","string",True),("key","string",True),("version_id","string",False)],
    "s3_create_presigned_url": [("bucket","string",True),("key","string",True),("expires_in","integer",False),("method","string",False)],
    "s3_create_bucket": [("bucket","string",True),("region","string",False),("acl","string",False)],
    "docusign_create_envelope": [("document_base64","string",True),("signers","array",True),("subject","string",True),("email_body","string",False)],
    "notion_create_page": [("parent_id","string",True),("title","string",True),("properties","object",False),("content","array",False)],
    "notion_query_database": [("database_id","string",True),("filter","object",False),("sorts","array",False),("page_size","integer",False)],
    "airtable_create_record": [("base_id","string",True),("table_name","string",True),("fields","object",True)],
    "airtable_list_records": [("base_id","string",True),("table_name","string",True),("filter_formula","string",False),("max_records","integer",False)],
}

# Attribute metadata shown in /attributes endpoint
ATTRIBUTES = [
    {"name": "payments",  "description": "Payment processing, billing, invoicing, and financial transactions"},
    {"name": "developer", "description": "Code repositories, CI/CD pipelines, issue tracking, and developer tools"},
    {"name": "messaging", "description": "Chat, SMS, email, and push notification delivery"},
    {"name": "crm",       "description": "Customer relationship management, support tickets, and contacts"},
    {"name": "identity",  "description": "Authentication, authorization, user management, and access control"},
    {"name": "analytics", "description": "Event tracking, metrics, dashboards, and business intelligence"},
    {"name": "storage",   "description": "File storage, document management, and object storage"},
]
